name: build-test

on:
  push:
    branches: 
      - covalent 
  pull_request:
    branches:
      - covalent

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify dependencies
      run: go mod verify
    
    - name: Lint
      run: make lint

    - name: Build all
      run: make all
      #run: go build -v ./...

    - name: Run tests
      run: make test
      #run: go test -race -vet=off ./...

    - name: Clean
      run: make clean

  # test-cache:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Install Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.17.x
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - uses: actions/cache@v2
  #     with:
  #       # In order:
  #       # * Module download cache
  #       # * Build cache (Linux)
  #       # * Build cache (Mac)
  #       # * Build cache (Windows)
  #       path: |
  #         ~/go/pkg/mod
  #         ~/.cache/go-build
  #         ~/Library/Caches/go-build
  #         %LocalAppData%\go-build
  #       key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #       restore-keys: |
  #         ${{ runner.os }}-go-
  #   - name: Test
  #     run: go test ./...
