name: docker-image-ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Login to GCR
#        if: ${{ !env.ACT }}
#        uses: docker/login-action@v3
#        with:
#          registry: gcr.io
#          username: _json_key
#          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
#          images: ghcr.io/${{ github.repository }},gcr.io/covalent-project/bsp-geth
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ env.ACT && 'false' || 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
      - name: Create release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false

    # - name: Start containers
    #   run: docker-compose -f "docker-compose.yml" up --build --remove-orphans --force-recreate --exit-code-from agent

    # - name: Check running bsp-geth
    #   run: docker inspect bsp-geth

    # - name: Check running containers
    #   run: docker ps

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down